master:
  push:
    - name: mzwing-cnb
      services:
        - docker
      env:
        IMAGE: &image ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/mzwing-cnb:latest
      lock:
        key: mzwing-cnb-image
        wait: true
        cancel-in-wait: true
      stages:
        - name: build and push image
          script: docker buildx build -f modules/hosts/nixos/mzwing-cnb/Dockerfile -t "$IMAGE" --output type=registry,compression=zstd,oci-mediatypes=true .

$:
  vscode:
    - docker:
        image: *image
      services:
        - vscode
        - docker
      stages:
        - name: register vscode server extensions
          script: vscode-server-extensions
        # AGENIX_KEY comes from the personal env vars set in CNB's workspace settings.
        - name: unlock secrets
          script: agenix-unlock
