{
  mzwing.features."darwin/packages" = {
    meta.platforms = ["darwin"];

    darwin = {pkgs, ...}: {
      environment.systemPackages = with pkgs; [
        act
        actionlint
        alejandra
        aria2
        any-nix-shell
        ast-grep
        bat
        bun
        caddy
        ccache
        clang-tools
        cmake
        cocoapods
        container
        create-dmg
        dart-bin
        defuddle
        deno
        devenv
        direnv
        doctl
        fastfetch
        fd
        ffmpeg-full
        ffmpegthumbnailer
        fish
        fzf
        gh
        ghostscript
        git
        git-extras
        glow
        gnupg
        go
        hydroxide
        imagemagick
        ios-deploy
        iproute2mac
        just
        kotlin-language-server
        libjpeg_turbo
        libogg
        libopenmpt
        libpng
        libvorbis
        llvmPackages.openmp
        luarocks
        macdylibbundler
        mas
        mpg123
        nano
        ninja
        nushell
        oxfmt
        oxlint
        p7zip
        pandoc
        payload-dumper-go
        procps
        pinentry_mac
        poppler
        poppler-utils
        procs
        qpdf
        rclone
        ripgrep
        rlottie
        rtk
        ruby
        ruff
        rustup
        scrcpy
        SDL2
        sdl3
        sleuthkit
        starship
        swift-format
        swiftlint
        tinymist
        tmux
        tokei
        tree
        typst
        typstyle
        upx
        uv
        vcpkg
        wgcf
        wget
        xcbeautify
        xcodegen
        yarn
        yazi
        zig
        zoxide
      ];
    };
  };
}
